# _config.yml

# Site settings
title: Your Site Title
description: >- 
  A short description of your site.
baseurl: "" # Do not include a trailing slash!
url: "https://your-site-url.com"

# CMS Integration
collections:
  - name: posts
    label: Posts
    folder: "_posts"
    identifier_field: title
    format: front_matter

# Markdown settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-paginate

# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Add CMS configuration
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Editor settings for Pages CMS
pages_cms:
  config:
    collections:
      posts:
        label: "Posts"
        folder: "_posts"
        format: "front_matter"
